feat: End to end refinance
maple-labs/contract-test-suite pull request #9
Opened 2021-11-16 21:52 UTC by JGcarv

2021-11-18 19:04 UTC, lucas-manuel requested changes
Looks good! Some suggestions

2021-11-18 19:04 UTC, lucas-manuel commented on contracts/test/RefinanceTest.t.sol
> +        // 5 BTC @ ~$58k = $290k = 29% collateralized, interest only
Need to update comment for 2BTC

2021-11-18 19:04 UTC, lucas-manuel commented on contracts/test/RefinanceTest.t.sol
> +        debtLocker.acceptNewTerms(address(refinancer), data, principalIncrease);
We should assert that this fails before the fundLoan is called with a try/catch

2021-11-18 19:04 UTC, lucas-manuel commented on contracts/test/RefinanceTest.t.sol
> +
Lets do another payment and claim after the refinance and explictly assert the values to show a change in the amount

2021-11-18 19:04 UTC, lucas-manuel commented on contracts/test/RefinanceTest.t.sol
> +
Lets also set endingPrincipal to be lower than 2m to demonstrate that we can move from interest-only to amortized using a refiannce

2021-11-19 20:10 UTC, JGcarv commented on contracts/test/RefinanceTest.t.sol
> +        /*****************/
I don't understand what do you mean here

2021-11-19 20:34 UTC, lucas-manuel commented on contracts/test/RefinanceTest.t.sol
> +        /*****************/
Like move
```js
/*****************/
/*** Fund Loan ***/
/*****************/
```
into the scoping block so its aligned with the drawdown label. The way it looks currently looks like the whole scoping block is for funding the loan

2021-11-23 16:37 UTC, lucas-manuel commented on contracts/test/RefinanceTest.t.sol
> +        // 2 BTC @ ~$58k = $290k = 29% collateralized, partially amortized
`2 BTC @ ~$58k = $116k = 11.6% collateralized, partially amortized`

2021-11-24 13:46 UTC, merged